# -*- coding: utf-8 -*-
"""Tool_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mdkpTAFfFCD8r-U-jD9sfgI2F1-H20im
"""

from sklearn.datasets import fetch_20newsgroups
def load_data(categories=None):
    return fetch_20newsgroups(subset='train', categories=categories, shuffle=True)