# -*- coding: utf-8 -*-
"""Tool_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_L9RhBmW2x5rzv8enrhXMRuVvTEp7zQ
"""

from sklearn.feature_extraction.text import CountVectorizer

from lime.lime_text import LimeTextExplainer

def make_predictor(model, vectorizer):
    def predictor(texts):
        return model.predict_proba(vectorizer.transform(texts))
    return predictor

def explain_prediction(text_sample, model, vectorizer, class_names):
    lte = LimeTextExplainer(class_names=class_names)
    show_me_magic = lte.explain_instance(text_sample, make_predictor(model, vectorizer))
    return show_me_magic